### ISSUE TITLE
java.lang.ClassCastException: net.minecraft.item.ItemSkull cannot be cast to net.minecraft.item.ItemArmor

### ISSUE THREAD

**Issue by thejims** [AleXndrTheGr8st/SimpleCore#6]
Client crashes instantly when wearing Dragon Head and connecting to server....

http://pastebin.com/h2jhKayh

**Comment by Sinhika** [comment]
Opened at https://github.com/Sinhika/SimpleCore, as this version is no longer being maintained, AFAIK.  Your crash is with my version.
